In [897]:
import pandas as pd
import requests
import matplotlib.pyplot as plt
import requests
import os
import numpy as np
from math import floor, ceil

pd.options.mode.chained_assignment = None
pd.set_option('display.max_rows', 200)

## Load Statistics

In [898]:
standings_df = pd.read_csv('../data/outputs/standings.csv')
standings_df.head(2)

,position,playedGames,form,won,draw,lost,points,goalsFor,goalsAgainst,goalDifference,team_short_name,team_group,competition
0,1,30,NaN,24,3,3,75,66,21,45,Napoli,0,Serie A
1,2,30,NaN,18,7,5,61,49,20,29,Lazio,0,Serie A

In [899]:
win_draw_loss = pd.read_csv('../data/outputs/win_draw_loss.csv')
win_draw_loss.head(2)

,main_team,team_group,competition,n_matches,avg_win,avg_draw,avg_loss,win_streak_weighted,draw_streak_weighted,loss_streak_weighted,tot_giornata,win_streak_weighted_ratio,draw_streak_weighted_ratio,loss_streak_weighted_ratio
0,Almeria,0,La Liga,11,0.090909,0.090909,0.818182,24.0,17.0,134.0,175.0,0.137143,0.097143,0.765714
1,Almeria,1,La Liga,11,0.363636,0.090909,0.545455,33.0,28.0,85.0,146.0,0.226027,0.191781,0.582192

In [900]:
win_draw_loss_away_home = pd.read_csv('../data/outputs/win_draw_loss_away_home.csv')
win_draw_loss_away_home.head(2)

,main_team,team_group,competition,away_home,n_matches,avg_win,avg_draw,avg_loss,win_streak_weighted,draw_streak_weighted,loss_streak_weighted,tot_giornata,win_streak_weighted_ratio,draw_streak_weighted_ratio,loss_streak_weighted_ratio
0,Almeria,0,La Liga,away,5,0.000000,0.000000,1.000000,0.0,0.0,70.0,70.0,0.000000,0.000000,1.000000
1,Almeria,0,La Liga,home,6,0.166667,0.166667,0.666667,24.0,17.0,64.0,105.0,0.228571,0.161905,0.609524

In [901]:
scored_conceded_goal_group_away_home= pd.read_csv('../data/outputs/team_scored_conceded_goal_group_away_home.csv')
scored_conceded_goal_group_away_home.head(2)

,main_team,team_group,competition,away_home,n_matches,team_has_scored,team_has_conceded_goal,team_has_scored_streak_weighted,team_has_conceded_goal_streak_weighted,tot_giornata,team_has_scored_streak_weighted_ratio,team_has_conceded_goal_streak_weighted_ratio,team_has_conceded_goal_ratio,team_has_scored_ratio
0,Almeria,0,La Liga,away,5,3,5,50.0,70.0,70.0,0.714286,1.000000,1.000000,0.600000
1,Almeria,0,La Liga,home,6,4,5,64.0,81.0,105.0,0.609524,0.771429,0.833333,0.666667

In [902]:
scored_conceded_goal_group = pd.read_csv('../data/outputs/team_scored_conceded_goal_group.csv')
scored_conceded_goal_group.head(2)

,main_team,team_group,competition,n_matches,team_has_scored,team_has_conceded_goal,team_has_scored_streak_weighted,team_has_conceded_goal_streak_weighted,tot_giornata,team_has_scored_streak_weighted_ratio,team_has_conceded_goal_streak_weighted_ratio,team_has_conceded_goal_ratio,team_has_scored_ratio
0,Almeria,0,La Liga,11,7,10,114.0,151.0,175.0,0.651429,0.862857,0.909091,0.636364
1,Almeria,1,La Liga,11,7,11,110.0,146.0,146.0,0.753425,1.000000,1.000000,0.636364

In [903]:
no_goal_group = pd.read_csv('../data/outputs/no_goal_group.csv')
no_goal_group.head(2)

,n_matches,main_team,team_group,competition,no_goal,no_goal_streak_weighted,goal_streak_weighted,tot_giornata,no_goal_streak_weighted_ratio,goal_streak_weighted_ratio,no_goal_ratio,goal_ratio,curr_giornata,last_giornata
0,11,Augsburg,0,Bundesliga,3,27.0,126.0,153.0,0.176471,0.823529,0.272727,0.727273,28,28.0
1,11,Augsburg,1,Bundesliga,4,48.0,118.0,166.0,0.289157,0.710843,0.363636,0.636364,28,28.0

In [904]:
no_goal_group_away_home = pd.read_csv('../data/outputs/no_goal_group_away_home.csv')
no_goal_group_away_home.head(2)

,main_team,team_group,away_home,competition,n_matches,no_goal,goal_streak_weighted,no_goal_streak_weighted,tot_giornata,goal_streak_weighted_ratio,no_goal_streak_weighted_ratio,no_goal_ratio,goal_ratio
0,Almeria,0,away,La Liga,5,2,50.0,20.0,70.0,0.714286,0.285714,0.4,0.6
1,Almeria,0,home,La Liga,6,3,40.0,65.0,105.0,0.380952,0.619048,0.5,0.5

In [905]:
n_goal_group = pd.read_csv('../data/outputs/num_goals_group.csv')
n_goal_group.head(2)

  main_team team_group competition  n_matches  avg_goal_fatti  avg_goal_subiti
0   Almeria          0     La Liga         11        0.727273         2.090909
1   Almeria          1     La Liga         11        1.454545         1.818182

In [906]:
n_goal_group_away_home = pd.read_csv('../data/outputs/n_goal_group_away_home.csv')
n_goal_group_away_home.head(2)

,main_team,away_home,team_group,competition,n_matches,avg_goal_fatti,avg_goal_subiti
0,Almeria,away,0,La Liga,5,0.600000,2.600000
1,Almeria,away,1,La Liga,6,0.833333,2.333333

In [907]:
n_goal_group_last_matches = pd.read_csv('../data/outputs/n_goal_group_last_matches.csv')
n_goal_group_last_matches.head(2)

,main_team,team_group,competition,n_matches,avg_goal_fatti,avg_goal_subiti,n_last_matches
0,Almeria,0,La Liga,4,1.00,1.75,10
1,Almeria,1,La Liga,4,1.25,3.00,10

### Next Matches

In [908]:
next_matches = pd.DataFrame([\
    ["Bundesliga","Augsburg","Stuttgart"],
    ["Bundesliga","Hoffenheim","FC Koln"],
    ["Bundesliga","Bochum","Wolfsburg"],
    ["Bundesliga","Hertha","Werder Bremen"],
    ["Bundesliga","Mainz","Bayern Munich"],
    ["Bundesliga","Dortmund","Ein Frankfurt"],
    ["Bundesliga","Freiburg","Schalke 04"],
    ["Bundesliga","Leverkusen","RB Leipzig"],
    ["Bundesliga","M'gladbach","Union Berlin"],
    ["La Liga","Espanol","Cadiz"],
    ["La Liga","Osasuna","Betis"],
    ["La Liga", "Almeria", "Ath Bilbao"],
    ["La Liga","Sociedad","Vallecano"],
    ["La Liga","Valladolid","Girona"],
    ["La Liga","Real Madrid","Celta"],
    ["La Liga","Elche","Valencia"],
    ["La Liga","Barcelona","Ath Madrid"],
    ["La Liga","Mallorca","Getafe"],
    ["La Liga","Sevilla","Villarreal"],
    ["Premier League","Arsenal","Southampton"],
    ["Premier League","Fulham","Leeds"],
    ["Premier League","Crystal Palace","Everton"],
    ["Premier League","Liverpool","Nott'm Forest"],
    ["Premier League","Brentford","Aston Villa"],
    ["Premier League","Leicester","Wolves"],
    ["Premier League","Newcastle","Tottenham"],
    ["Premier League","Bournemouth","West Ham"],
    ["Serie A","Verona","Bologna"],
    ["Serie A","Salernitana","Sassuolo"],
    ["Serie A","Lazio","Torino"],
    ["Serie A","Sampdoria","Spezia"],
    ["Serie A","Empoli","Inter"],
    ["Serie A","Monza","Fiorentina"],
    ["Serie A","Udinese","Cremonese"],
    ["Serie A","Milan","Lecce"],
    ["Serie A","Juventus","Napoli"],
    ["Serie A","Atalanta","Roma"]],\
    columns=['competition','home_team','away_team'])

#### Check names are spelled correctly

In [909]:
dd = next_matches.merge(standings_df, left_on='home_team', right_on='team_short_name', how='left')
assert len(dd[dd.position.isna()]['home_team'])==0, dd[dd.position.isna()]['home_team']

In [910]:
dd = next_matches.merge(standings_df, left_on='away_team', right_on='team_short_name', how='left')
assert len(dd[dd.position.isna()]['away_team']) == 0, dd[dd.position.isna()]['away_team']

#### Assign team groups

In [911]:
next_matches_with_group = next_matches.merge(standings_df[['competition','team_short_name','team_group']],\
                   left_on=['competition','home_team'],\
                   right_on=['competition','team_short_name'], how='left')\
            .merge(standings_df[['competition','team_short_name','team_group']],\
                   left_on=['competition','away_team'],\
                   right_on=['competition','team_short_name'], how='left', suffixes=['_home','_away'])\
            [['competition','home_team','away_team','team_group_home','team_group_away']]
next_matches_with_group['team_group_home'] = next_matches_with_group['team_group_home'].astype(str)
next_matches_with_group['team_group_away'] = next_matches_with_group['team_group_away'].astype(str)

### NoGoal/Goal Overall

In [912]:
nggall = no_goal_group[no_goal_group.team_group=='all']

In [913]:
nggall.columns

Index(['n_matches', 'main_team', 'team_group', 'competition', 'no_goal',
       'no_goal_streak_weighted', 'goal_streak_weighted', 'tot_giornata',
       'no_goal_streak_weighted_ratio', 'goal_streak_weighted_ratio',
       'no_goal_ratio', 'goal_ratio', 'curr_giornata', 'last_giornata'],
      dtype='object')

In [914]:
dd1 = next_matches.merge(nggall, left_on=['competition','home_team'], right_on=['competition','main_team'])
dd1 = dd1.merge(nggall, left_on=['competition','away_team'], right_on=['competition','main_team'], suffixes=['_home','_away'])
dd1['no_goal_streak_weighted_ratio'] = dd1['no_goal_streak_weighted_ratio_home'] + dd1['no_goal_streak_weighted_ratio_away']
dd1['goal_streak_weighted_ratio'] = dd1['goal_streak_weighted_ratio_home'] + dd1['goal_streak_weighted_ratio_away']
dd1['no_goal_ratio'] = dd1['no_goal_ratio_home'] + dd1['no_goal_ratio_away']

#### NoGoal

In [941]:
ngall = dd1[['competition','home_team','away_team',\
    'no_goal_ratio_home','no_goal_ratio_away',\
    'no_goal_ratio']].sort_values('no_goal_ratio', ascending=False).head(10)
ngall

,competition,home_team,away_team,no_goal_ratio_home,no_goal_ratio_away,no_goal_ratio
27,Serie A,Juventus,Napoli,0.733333,0.600000,1.333333
16,La Liga,Barcelona,Ath Madrid,0.793103,0.517241,1.310345
17,La Liga,Mallorca,Getafe,0.655172,0.551724,1.206897
21,Serie A,Lazio,Torino,0.666667,0.466667,1.133333
22,Serie A,Sampdoria,Spezia,0.600000,0.533333,1.133333
2,Bundesliga,Bochum,Wolfsburg,0.535714,0.571429,1.107143
10,La Liga,Osasuna,Betis,0.586207,0.517241,1.103448
15,La Liga,Elche,Valencia,0.517241,0.551724,1.068966
28,Serie A,Atalanta,Roma,0.466667,0.600000,1.066667
23,Serie A,Empoli,Inter,0.566667,0.500000,1.066667

#### NoGoal Streak Weighted

In [942]:
ngallsw = dd1[['competition','home_team','away_team',\
    'no_goal_streak_weighted_ratio_home','no_goal_streak_weighted_ratio_away',\
    'no_goal_streak_weighted_ratio']].sort_values('no_goal_streak_weighted_ratio', ascending=False).head(10)
ngallsw

,competition,home_team,away_team,no_goal_streak_weighted_ratio_home,no_goal_streak_weighted_ratio_away,no_goal_streak_weighted_ratio
27,Serie A,Juventus,Napoli,0.720430,0.701075,1.421505
16,La Liga,Barcelona,Ath Madrid,0.805804,0.516854,1.322658
17,La Liga,Mallorca,Getafe,0.676404,0.573034,1.249438
21,Serie A,Lazio,Torino,0.724731,0.496774,1.221505
23,Serie A,Empoli,Inter,0.602151,0.587097,1.189247
15,La Liga,Elche,Valencia,0.541573,0.597753,1.139326
2,Bundesliga,Bochum,Wolfsburg,0.544335,0.583744,1.128079
12,La Liga,Sociedad,Vallecano,0.667416,0.429213,1.096629
10,La Liga,Osasuna,Betis,0.595506,0.493304,1.088809
22,Serie A,Sampdoria,Spezia,0.563441,0.518280,1.081720

#### Goal Streak Weighted

In [943]:
gallsw = dd1[['competition','home_team','away_team',\
    'goal_streak_weighted_ratio_home','goal_streak_weighted_ratio_away',\
    'goal_streak_weighted_ratio']].sort_values('goal_streak_weighted_ratio', ascending=False).head(10)
gallsw

,competition,home_team,away_team,goal_streak_weighted_ratio_home,goal_streak_weighted_ratio_away,goal_streak_weighted_ratio
0,Bundesliga,Augsburg,Stuttgart,0.711823,0.672414,1.384236
4,Bundesliga,Mainz,Bayern Munich,0.679803,0.692118,1.371921
5,Bundesliga,Dortmund,Ein Frankfurt,0.677340,0.682266,1.359606
3,Bundesliga,Hertha,Werder Bremen,0.650246,0.689655,1.339901
9,La Liga,Espanol,Cadiz,0.820225,0.359551,1.179775
20,Serie A,Salernitana,Sassuolo,0.604301,0.548387,1.152688
25,Serie A,Udinese,Cremonese,0.572043,0.574194,1.146237
1,Bundesliga,Hoffenheim,FC Koln,0.672414,0.453202,1.125616
7,Bundesliga,Leverkusen,RB Leipzig,0.573892,0.546798,1.120690
11,La Liga,Almeria,Ath Bilbao,0.696629,0.408989,1.105618

### NoGoal/Goal Group

In [944]:
dd2 = next_matches_with_group.merge(no_goal_group,\
                    left_on=['competition','home_team','team_group_away'],
                    right_on=['competition','main_team','team_group']).drop(columns=['team_group'])\
                        .merge(no_goal_group,\
                    left_on=['competition','away_team','team_group_home'],
                    right_on=['competition','main_team','team_group'], suffixes=['_home','_away'])
dd2['no_goal_streak_weighted_ratio'] = dd2['no_goal_streak_weighted_ratio_home'] + dd2['no_goal_streak_weighted_ratio_away']
dd2['goal_streak_weighted_ratio'] = dd2['goal_streak_weighted_ratio_home'] + dd2['goal_streak_weighted_ratio_away']
dd2['no_goal_ratio'] = dd2['no_goal_ratio_home'] + dd2['no_goal_ratio_away']

#### No Goal Home/Away

In [945]:
nggrpah = dd2[(dd2['n_matches_home'] > 6)&(dd2['n_matches_away']>6)]\
    [['competition','home_team','away_team',\
    'no_goal_ratio_home','no_goal_ratio_away',\
    'no_goal_ratio','n_matches_home','n_matches_away']]\
    .sort_values('no_goal_ratio', ascending=False).head(10)
nggrpah

,competition,home_team,away_team,no_goal_ratio_home,no_goal_ratio_away,no_goal_ratio,n_matches_home,n_matches_away
6,Bundesliga,Freiburg,Schalke 04,0.571429,0.700000,1.271429,7,10
21,Serie A,Lazio,Torino,0.700000,0.545455,1.245455,10,11
10,La Liga,Osasuna,Betis,0.777778,0.400000,1.177778,9,10
28,Serie A,Atalanta,Roma,0.555556,0.555556,1.111111,9,9
16,La Liga,Barcelona,Ath Madrid,0.555556,0.555556,1.111111,9,9
23,Serie A,Empoli,Inter,0.636364,0.454545,1.090909,11,11
27,Serie A,Juventus,Napoli,0.555556,0.500000,1.055556,9,10
11,La Liga,Almeria,Ath Bilbao,0.454545,0.500000,0.954545,11,10
12,La Liga,Sociedad,Vallecano,0.500000,0.444444,0.944444,10,9
18,La Liga,Sevilla,Villarreal,0.333333,0.600000,0.933333,9,10

#### NoGoal Streak Weighted

In [946]:
nggrpsw = dd2[(dd2['n_matches_home'] > 6)&(dd2['n_matches_away']>6)]\
    [['competition','home_team','away_team',\
    'no_goal_streak_weighted_ratio_home','no_goal_streak_weighted_ratio_away',\
    'no_goal_streak_weighted_ratio','n_matches_home','n_matches_away']]\
    .sort_values('no_goal_streak_weighted_ratio', ascending=False).head(10)
nggrpsw

,competition,home_team,away_team,no_goal_streak_weighted_ratio_home,no_goal_streak_weighted_ratio_away,no_goal_streak_weighted_ratio,n_matches_home,n_matches_away
21,Serie A,Lazio,Torino,0.737931,0.603774,1.341705,10,11
28,Serie A,Atalanta,Roma,0.647482,0.633588,1.281070,9,9
23,Serie A,Empoli,Inter,0.691489,0.569149,1.260638,11,11
16,La Liga,Barcelona,Ath Madrid,0.594406,0.634146,1.228552,9,9
10,La Liga,Osasuna,Betis,0.842105,0.357143,1.199248,9,10
27,Serie A,Juventus,Napoli,0.563291,0.627219,1.190510,9,10
6,Bundesliga,Freiburg,Schalke 04,0.421053,0.701987,1.123039,7,10
14,La Liga,Real Madrid,Celta,0.635036,0.421053,1.056089,10,10
17,La Liga,Mallorca,Getafe,0.541667,0.407143,0.948810,8,10
12,La Liga,Sociedad,Vallecano,0.487013,0.459854,0.946867,10,9

#### Goal Streak Weighted

In [947]:
ggrpsw = dd2[['competition','home_team','away_team',\
    'goal_streak_weighted_ratio_home','goal_streak_weighted_ratio_away',\
    'goal_streak_weighted_ratio','n_matches_home','n_matches_away']]\
    .sort_values('goal_streak_weighted_ratio', ascending=False).head(10)
ggrpsw

,competition,home_team,away_team,goal_streak_weighted_ratio_home,goal_streak_weighted_ratio_away,goal_streak_weighted_ratio,n_matches_home,n_matches_away
4,Bundesliga,Mainz,Bayern Munich,0.797468,0.874214,1.671682,11,11
26,Serie A,Milan,Lecce,0.864078,0.786127,1.650205,7,11
24,Serie A,Monza,Fiorentina,0.766423,0.768519,1.534942,9,8
5,Bundesliga,Dortmund,Ein Frankfurt,0.771242,0.737931,1.509173,11,10
9,La Liga,Espanol,Cadiz,0.729412,0.762295,1.491707,6,7
19,Serie A,Verona,Bologna,0.725000,0.741667,1.466667,11,9
7,Bundesliga,Leverkusen,RB Leipzig,0.631206,0.809917,1.441123,10,9
8,Bundesliga,M'gladbach,Union Berlin,0.640719,0.728571,1.369290,11,10
13,La Liga,Valladolid,Girona,0.335766,0.963415,1.299181,9,7
1,Bundesliga,Hoffenheim,FC Koln,0.644444,0.644578,1.289023,10,10

##### Only for more than 5 matches

In [948]:
ggrpswnmatch = dd3 = dd2[(dd2['n_matches_home'] > 5)&(dd2['n_matches_away'] > 5)]
dd3[['competition','home_team','away_team',\
    'goal_streak_weighted_ratio_home','goal_streak_weighted_ratio_away',\
    'goal_streak_weighted_ratio']].sort_values('goal_streak_weighted_ratio', ascending=False).head(10)
ggrpswnmatch

,competition,home_team,away_team,team_group_home,team_group_away,n_matches_home,main_team_home,no_goal_home,no_goal_streak_weighted_home,goal_streak_weighted_home,...,tot_giornata_away,no_goal_streak_weighted_ratio_away,goal_streak_weighted_ratio_away,no_goal_ratio_away,goal_ratio_away,curr_giornata_away,last_giornata_away,no_goal_streak_weighted_ratio,goal_streak_weighted_ratio,no_goal_ratio
0,Bundesliga,Augsburg,Stuttgart,1,2,6,Augsburg,3,42.0,45.0,...,137.0,0.503650,0.496350,0.400000,0.600000,28,28.0,0.986408,1.013592,0.900000
1,Bundesliga,Hoffenheim,FC Koln,1,1,10,Hoffenheim,3,48.0,87.0,...,166.0,0.355422,0.644578,0.300000,0.700000,28,28.0,0.710977,1.289023,0.600000
2,Bundesliga,Bochum,Wolfsburg,2,1,11,Bochum,5,78.0,61.0,...,85.0,0.905882,0.094118,0.833333,0.166667,28,28.0,1.467033,0.532967,1.287879
3,Bundesliga,Hertha,Werder Bremen,2,1,11,Hertha,6,74.0,84.0,...,73.0,0.794521,0.205479,0.666667,0.333333,28,28.0,1.262875,0.737125,1.212121
4,Bundesliga,Mainz,Bayern Munich,1,0,11,Mainz,3,32.0,126.0,...,159.0,0.125786,0.874214,0.272727,0.727273,28,28.0,0.328318,1.671682,0.545455
5,Bundesliga,Dortmund,Ein Frankfurt,0,0,11,Dortmund,4,35.0,118.0,...,145.0,0.262069,0.737931,0.300000,0.700000,28,28.0,0.490827,1.509173,0.663636
6,Bundesliga,Freiburg,Schalke 04,0,2,7,Freiburg,4,40.0,55.0,...,151.0,0.701987,0.298013,0.700000,0.300000,28,28.0,1.123039,0.876961,1.271429
7,Bundesliga,Leverkusen,RB Leipzig,0,0,10,Leverkusen,5,52.0,89.0,...,121.0,0.190083,0.809917,0.333333,0.666667,28,28.0,0.558877,1.441123,0.833333
8,Bundesliga,M'gladbach,Union Berlin,1,0,11,M'gladbach,4,60.0,107.0,...,140.0,0.271429,0.728571,0.400000,0.600000,28,28.0,0.630710,1.369290,0.763636
9,La Liga,Espanol,Cadiz,2,2,6,Espanol,1,23.0,62.0,...,122.0,0.237705,0.762295,0.285714,0.714286,30,30.0,0.508293,1.491707,0.452381
10,La Liga,Osasuna,Betis,1,0,9,Osasuna,7,112.0,21.0,...,126.0,0.357143,0.642857,0.400000,0.600000,30,30.0,1.199248,0.800752,1.177778
11,La Liga,Almeria,Ath Bilbao,2,0,11,Almeria,5,85.0,90.0,...,131.0,0.335878,0.664122,0.500000,0.500000,30,30.0,0.821592,1.178408,0.954545
12,La Liga,Sociedad,Vallecano,0,1,10,Sociedad,5,75.0,79.0,...,137.0,0.459854,0.540146,0.444444,0.555556,30,30.0,0.946867,1.053133,0.944444
13,La Liga,Valladolid,Girona,1,1,9,Valladolid,5,91.0,46.0,...,82.0,0.036585,0.963415,0.142857,0.857143,30,30.0,0.700819,1.299181,0.698413
14,La Liga,Real Madrid,Celta,0,1,10,Real Madrid,4,87.0,50.0,...,133.0,0.421053,0.578947,0.400000,0.600000,30,30.0,1.056089,0.943911,0.800000
15,La Liga,Elche,Valencia,2,2,6,Elche,2,35.0,39.0,...,106.0,0.367925,0.632075,0.285714,0.714286,30,30.0,0.840898,1.159102,0.619048
16,La Liga,Barcelona,Ath Madrid,0,0,9,Barcelona,5,85.0,58.0,...,123.0,0.634146,0.365854,0.555556,0.444444,30,30.0,1.228552,0.771448,1.111111
17,La Liga,Mallorca,Getafe,1,2,8,Mallorca,4,65.0,55.0,...,140.0,0.407143,0.592857,0.400000,0.600000,30,30.0,0.948810,1.051190,0.900000
18,La Liga,Sevilla,Villarreal,1,0,9,Sevilla,3,32.0,77.0,...,163.0,0.533742,0.466258,0.600000,0.400000,30,30.0,0.827320,1.172680,0.933333
19,Serie A,Verona,Bologna,2,1,11,Verona,3,44.0,116.0,...,120.0,0.258333,0.741667,0.222222,0.777778,30,30.0,0.533333,1.466667,0.494949
20,Serie A,Salernitana,Sassuolo,2,1,10,Salernitana,4,49.0,97.0,...,150.0,0.440000,0.560000,0.500000,0.500000,30,30.0,0.775616,1.224384,0.900000
21,Serie A,Lazio,Torino,0,1,10,Lazio,7,107.0,38.0,...,159.0,0.603774,0.396226,0.545455,0.454545,30,30.0,1.341705,0.658295,1.245455
22,Serie A,Sampdoria,Spezia,2,2,9,Sampdoria,4,54.0,98.0,...,113.0,0.469027,0.530973,0.428571,0.571429,30,30.0,0.824290,1.175710,0.873016
23,Serie A,Empoli,Inter,1,0,11,Empoli,7,130.0,58.0,...,188.0,0.569149,0.430851,0.454545,0.545455,30,30.0,1.260638,0.739362,1.090909
24,Serie A,Monza,Fiorentina,1,1,9,Monza,2,32.0,105.0,...,108.0,0.231481,0.768519,0.375000,0.625000,30,30.0,0.465058,1.534942,0.597222
25,Serie A,Udinese,Cremonese,1,2,8,Udinese,3,33.0,79.0,...,204.0,0.431373,0.568627,0.416667,0.583333,30,30.0,0.726015,1.273985,0.791667
26,Serie A,Milan,Lecce,0,2,7,Milan,1,14.0,89.0,...,173.0,0.213873,0.786127,0.181818,0.818182,30,30.0,0.349795,1.650205,0.324675
27,Serie A,Juventus,Napoli,0,0,9,Juventus,5,89.0,69.0,...,169.0,0.627219,0.372781,0.500000,0.500000,30,30.0,1.190510,0.809490,1.055556
28,Serie A,Atalanta,Roma,0,0,9,Atalanta,5,90.0,49.0,...,131.0,0.633588,0.366412,0.555556,0.444444,30,30.0,1.281070,0.718930,1.111111

#### Common

In [961]:
keycols = ['competition','home_team','away_team']
ngall.merge(ngallsw[keycols], on=keycols)\
     .merge(nggrpsw[keycols], on=keycols)

,competition,home_team,away_team,no_goal_ratio_home,no_goal_ratio_away,no_goal_ratio
0,Serie A,Juventus,Napoli,0.733333,0.600000,1.333333
1,La Liga,Barcelona,Ath Madrid,0.793103,0.517241,1.310345
2,La Liga,Mallorca,Getafe,0.655172,0.551724,1.206897
3,Serie A,Lazio,Torino,0.666667,0.466667,1.133333
4,La Liga,Osasuna,Betis,0.586207,0.517241,1.103448
5,Serie A,Empoli,Inter,0.566667,0.500000,1.066667

In [963]:
ngall.merge(ngallsw[keycols], on=keycols)\
     .merge(nggrpah[keycols], on=keycols)

,competition,home_team,away_team,no_goal_ratio_home,no_goal_ratio_away,no_goal_ratio
0,Serie A,Juventus,Napoli,0.733333,0.600000,1.333333
1,La Liga,Barcelona,Ath Madrid,0.793103,0.517241,1.310345
2,Serie A,Lazio,Torino,0.666667,0.466667,1.133333
3,La Liga,Osasuna,Betis,0.586207,0.517241,1.103448
4,Serie A,Empoli,Inter,0.566667,0.500000,1.066667

In [964]:
ngall.merge(ngallsw[keycols], on=keycols)\
     .merge(nggrpah[keycols], on=keycols)\
     .merge(nggrpsw[keycols], on=keycols)

,competition,home_team,away_team,no_goal_ratio_home,no_goal_ratio_away,no_goal_ratio
0,Serie A,Juventus,Napoli,0.733333,0.600000,1.333333
1,La Liga,Barcelona,Ath Madrid,0.793103,0.517241,1.310345
2,Serie A,Lazio,Torino,0.666667,0.466667,1.133333
3,La Liga,Osasuna,Betis,0.586207,0.517241,1.103448
4,Serie A,Empoli,Inter,0.566667,0.500000,1.066667

### N° Goals - OVER

#### Group

In [923]:
dd2 = next_matches_with_group.merge(n_goal_group,\
                    left_on=['competition','home_team','team_group_away'],
                    right_on=['competition','main_team','team_group']).drop(columns=['team_group'])\
                        .merge(n_goal_group,\
                    left_on=['competition','away_team','team_group_home'],
                    right_on=['competition','main_team','team_group'], suffixes=['_home','_away'])
dd2['avg_goal_fatti_tot'] = dd2['avg_goal_fatti_home'] + dd2['avg_goal_fatti_away']
dd2['avg_goal_subiti_tot'] = dd2['avg_goal_subiti_home'] + dd2['avg_goal_subiti_away']
dd2['min_fatti_subiti_tot'] = \
            dd2.apply(lambda row: floor(min(row['avg_goal_fatti_tot'],row['avg_goal_subiti_tot'])), axis=1)

In [924]:
dd2[['competition','home_team','away_team',\
    'avg_goal_fatti_tot','avg_goal_subiti_tot','min_fatti_subiti_tot',\
     'n_matches_home','n_matches_away']]\
    .sort_values('min_fatti_subiti_tot', ascending=False).head(10)

,competition,home_team,away_team,avg_goal_fatti_tot,avg_goal_subiti_tot,min_fatti_subiti_tot,n_matches_home,n_matches_away
19,Premier League,Arsenal,Southampton,3.227273,3.163636,3,10,11
1,Bundesliga,Hoffenheim,FC Koln,3.300000,3.600000,3,10,10
4,Bundesliga,Mainz,Bayern Munich,4.000000,3.181818,3,11,11
5,Bundesliga,Dortmund,Ein Frankfurt,3.609091,3.254545,3,11,10
20,Premier League,Fulham,Leeds,3.500000,3.527778,3,9,12
26,Premier League,Bournemouth,West Ham,2.725000,2.375000,2,8,10
21,Premier League,Crystal Palace,Everton,2.373737,2.161616,2,9,11
22,Premier League,Liverpool,Nott'm Forest,2.975000,2.150000,2,8,10
23,Premier League,Brentford,Aston Villa,2.754545,3.400000,2,11,10
24,Premier League,Leicester,Wolves,2.190909,2.954545,2,11,10

#### Group - Home/Away

In [925]:
n_goal_group_away_home.head(1)

,main_team,away_home,team_group,competition,n_matches,avg_goal_fatti,avg_goal_subiti
0,Almeria,away,0,La Liga,5,0.6,2.6

In [926]:
dd2 = next_matches_with_group.merge(n_goal_group_away_home[n_goal_group_away_home.away_home=='home'],\
                    left_on=['competition','home_team','team_group_away'],
                    right_on=['competition','main_team','team_group']).drop(columns=['team_group'])\
                        .merge(n_goal_group_away_home[n_goal_group_away_home.away_home=='away'],\
                    left_on=['competition','away_team','team_group_home'],
                    right_on=['competition','main_team','team_group'], suffixes=['_home','_away'])
dd2['avg_goal_fatti_tot'] = dd2['avg_goal_fatti_home'] + dd2['avg_goal_fatti_away']
dd2['avg_goal_subiti_tot'] = dd2['avg_goal_subiti_home'] + dd2['avg_goal_subiti_away']
dd2['min_fatti_subiti_tot'] = \
            dd2.apply(lambda row: floor(min(row['avg_goal_fatti_tot'],row['avg_goal_subiti_tot'])), axis=1)

In [927]:
dd3 = dd2[dd2.min_fatti_subiti_tot >= 2]
dd3[['competition','home_team','away_team',\
    'avg_goal_fatti_tot','avg_goal_subiti_tot','min_fatti_subiti_tot',\
     'n_matches_home','n_matches_away']]\
    .sort_values(['min_fatti_subiti_tot','avg_goal_subiti_tot','avg_goal_fatti_tot'], ascending=False).head(100)

,competition,home_team,away_team,avg_goal_fatti_tot,avg_goal_subiti_tot,min_fatti_subiti_tot,n_matches_home,n_matches_away
1,Bundesliga,Hoffenheim,FC Koln,3.850000,5.050000,3,5,4
7,Bundesliga,Leverkusen,RB Leipzig,3.066667,4.066667,3,5,3
27,Serie A,Verona,Bologna,3.000000,3.416667,3,4,3
25,Premier League,Newcastle,Tottenham,4.000000,3.250000,3,3,4
14,La Liga,Real Madrid,Celta,4.500000,3.050000,3,5,4
19,Premier League,Arsenal,Southampton,4.250000,3.050000,3,5,4
31,Serie A,Empoli,Inter,2.300000,4.250000,2,4,5
23,Premier League,Brentford,Aston Villa,2.550000,3.400000,2,5,4
36,Serie A,Atalanta,Roma,2.200000,3.400000,2,4,5
18,La Liga,Sevilla,Villarreal,2.750000,3.250000,2,4,4
33,Serie A,Udinese,Cremonese,2.333333,3.000000,2,4,6
29,Serie A,Lazio,Torino,2.033333,2.966667,2,5,6
4,Bundesliga,Mainz,Bayern Munich,2.666667,2.833333,2,6,4
5,Bundesliga,Dortmund,Ein Frankfurt,3.200000,2.800000,2,5,5
13,La Liga,Valladolid,Girona,3.250000,2.750000,2,4,2
20,Premier League,Fulham,Leeds,2.800000,2.700000,2,4,5
11,La Liga,Almeria,Ath Bilbao,3.633333,2.666667,2,6,5
34,Serie A,Milan,Lecce,2.500000,2.500000,2,2,4
30,Serie A,Sampdoria,Spezia,2.250000,2.500000,2,4,2
9,La Liga,Espanol,Cadiz,2.666667,2.333333,2,2,3
21,Premier League,Crystal Palace,Everton,2.266667,2.266667,2,3,5
28,Serie A,Salernitana,Sassuolo,3.000000,2.250000,2,4,4
8,Bundesliga,M'gladbach,Union Berlin,3.166667,2.166667,2,6,4
22,Premier League,Liverpool,Nott'm Forest,2.133333,2.133333,2,5,3

##### At least 5 matches

In [928]:
n_matches = 4

In [929]:
dd3 = dd2[(dd2.n_matches_home>n_matches)&(dd2.n_matches_away>n_matches)]
dd3 = dd3[dd3.min_fatti_subiti_tot >= 2]
dd3[['competition','home_team','away_team',\
    'avg_goal_fatti_tot','avg_goal_subiti_tot','min_fatti_subiti_tot',\
     'n_matches_home','n_matches_away']]\
    .sort_values(['min_fatti_subiti_tot','avg_goal_subiti_tot','avg_goal_fatti_tot'], ascending=False).head(100)

,competition,home_team,away_team,avg_goal_fatti_tot,avg_goal_subiti_tot,min_fatti_subiti_tot,n_matches_home,n_matches_away
29,Serie A,Lazio,Torino,2.033333,2.966667,2,5,6
5,Bundesliga,Dortmund,Ein Frankfurt,3.200000,2.800000,2,5,5
11,La Liga,Almeria,Ath Bilbao,3.633333,2.666667,2,6,5

#### Last Matches

##### Group

In [930]:
dd2 = next_matches_with_group.merge(n_goal_group_last_matches,\
                    left_on=['competition','home_team','team_group_away'],
                    right_on=['competition','main_team','team_group']).drop(columns=['team_group'])\
                        .merge(n_goal_group_last_matches,\
                    left_on=['competition','away_team','team_group_home'],
                    right_on=['competition','main_team','team_group'], suffixes=['_home','_away'])
dd2['min_goal_fatti_home_subiti_away'] = \
            dd2.apply(lambda row: min(row['avg_goal_fatti_home'],row['avg_goal_subiti_away']), axis=1)
dd2['min_goal_fatti_away_subiti_home'] = \
            dd2.apply(lambda row: min(row['avg_goal_fatti_away'],row['avg_goal_subiti_home']), axis=1)
dd2['min_fatti_subiti'] = dd2['min_goal_fatti_home_subiti_away'] + dd2['min_goal_fatti_away_subiti_home']
dd2['min_fatti_subiti_floor'] = dd2['min_fatti_subiti'].apply(floor)

In [931]:
dd3 = dd2[dd2.min_fatti_subiti_floor>1]
ddgroup = dd3[['competition','home_team','away_team',\
     'min_fatti_subiti_floor','min_fatti_subiti',\
    'min_goal_fatti_away_subiti_home','min_goal_fatti_home_subiti_away',\
     'n_matches_home','n_matches_away']]\
    .sort_values(['min_fatti_subiti_floor','min_fatti_subiti'], ascending=False)
ddgroup

,competition,home_team,away_team,min_fatti_subiti_floor,min_fatti_subiti,min_goal_fatti_away_subiti_home,min_goal_fatti_home_subiti_away,n_matches_home,n_matches_away
19,Premier League,Arsenal,Southampton,3,3.333333,1.000000,2.333333,3,3
4,Bundesliga,Mainz,Bayern Munich,3,3.250000,1.250000,2.000000,4,4
13,La Liga,Valladolid,Girona,3,3.000000,2.000000,1.000000,3,1
5,Bundesliga,Dortmund,Ein Frankfurt,2,3.000000,0.666667,2.333333,4,3
33,Serie A,Udinese,Cremonese,2,2.800000,1.200000,1.600000,1,5
7,Bundesliga,Leverkusen,RB Leipzig,2,2.666667,1.000000,1.666667,3,3
27,Serie A,Verona,Bologna,2,2.666667,1.666667,1.000000,3,2
11,La Liga,Almeria,Ath Bilbao,2,2.500000,1.750000,0.750000,4,4
18,La Liga,Sevilla,Villarreal,2,2.500000,2.000000,0.500000,2,3
20,Premier League,Fulham,Leeds,2,2.500000,1.000000,1.500000,2,4
32,Serie A,Monza,Fiorentina,2,2.500000,1.000000,1.500000,3,2
6,Bundesliga,Freiburg,Schalke 04,2,2.333333,0.666667,1.666667,3,3
21,Premier League,Crystal Palace,Everton,2,2.333333,0.666667,1.666667,3,3
25,Premier League,Newcastle,Tottenham,2,2.333333,1.666667,0.666667,3,1
24,Premier League,Leicester,Wolves,2,2.250000,1.500000,0.750000,4,2
10,La Liga,Osasuna,Betis,2,2.000000,2.000000,0.000000,2,3
14,La Liga,Real Madrid,Celta,2,2.000000,0.333333,1.666667,3,3
17,La Liga,Mallorca,Getafe,2,2.000000,1.500000,0.500000,2,3
22,Premier League,Liverpool,Nott'm Forest,2,2.000000,1.000000,1.000000,1,1
23,Premier League,Brentford,Aston Villa,2,2.000000,2.000000,0.000000,3,3
28,Serie A,Salernitana,Sassuolo,2,2.000000,1.000000,1.000000,3,4
34,Serie A,Milan,Lecce,2,2.000000,1.000000,1.000000,1,4

##### Overall

In [932]:
dd2 = next_matches_with_group.merge(n_goal_group_last_matches[n_goal_group_last_matches.team_group=='all'],\
                    left_on=['competition','home_team'],
                    right_on=['competition','main_team']).drop(columns=['team_group'])\
                        .merge(n_goal_group_last_matches[n_goal_group_last_matches.team_group=='all'],\
                    left_on=['competition','away_team'],
                    right_on=['competition','main_team'], suffixes=['_home','_away'])
dd2['min_goal_fatti_home_subiti_away'] = \
            dd2.apply(lambda row: min(row['avg_goal_fatti_home'],row['avg_goal_subiti_away']), axis=1)
dd2['min_goal_fatti_away_subiti_home'] = \
            dd2.apply(lambda row: min(row['avg_goal_fatti_away'],row['avg_goal_subiti_home']), axis=1)
dd2['min_fatti_subiti'] = dd2['min_goal_fatti_home_subiti_away'] + dd2['min_goal_fatti_away_subiti_home']
dd2['min_fatti_subiti_floor'] = dd2['min_fatti_subiti'].apply(floor)

In [933]:
dd3 = dd2[dd2.min_fatti_subiti_floor>1]
ddoverall = dd3[['competition','home_team','away_team',\
     'min_fatti_subiti_floor','min_fatti_subiti',\
    'min_goal_fatti_away_subiti_home','min_goal_fatti_home_subiti_away',\
     'n_matches_home','n_matches_away']]\
    .sort_values(['min_fatti_subiti_floor','min_fatti_subiti'], ascending=False)
ddoverall

,competition,home_team,away_team,min_fatti_subiti_floor,min_fatti_subiti,min_goal_fatti_away_subiti_home,min_goal_fatti_home_subiti_away,n_matches_home,n_matches_away
18,La Liga,Sevilla,Villarreal,3,3.100000,1.700,1.400000,10,10
13,La Liga,Valladolid,Girona,2,2.900000,1.800,1.100000,10,10
22,Premier League,Liverpool,Nott'm Forest,2,2.875000,0.750,2.125000,8,8
0,Bundesliga,Augsburg,Stuttgart,2,2.700000,1.300,1.400000,10,10
3,Bundesliga,Hertha,Werder Bremen,2,2.700000,1.400,1.300000,10,10
5,Bundesliga,Dortmund,Ein Frankfurt,2,2.700000,1.200,1.500000,10,10
25,Premier League,Newcastle,Tottenham,2,2.625000,1.375,1.250000,8,8
26,Premier League,Bournemouth,West Ham,2,2.625000,1.250,1.375000,8,8
4,Bundesliga,Mainz,Bayern Munich,2,2.400000,1.000,1.400000,10,10
11,La Liga,Almeria,Ath Bilbao,2,2.400000,1.500,0.900000,10,10
20,Premier League,Fulham,Leeds,2,2.392857,1.250,1.142857,7,8
21,Premier League,Crystal Palace,Everton,2,2.375000,1.000,1.375000,8,8
6,Bundesliga,Freiburg,Schalke 04,2,2.300000,1.200,1.100000,10,10
33,Serie A,Udinese,Cremonese,2,2.300000,1.200,1.100000,10,10
23,Premier League,Brentford,Aston Villa,2,2.250000,1.625,0.625000,8,8
2,Bundesliga,Bochum,Wolfsburg,2,2.200000,1.000,1.200000,10,10
7,Bundesliga,Leverkusen,RB Leipzig,2,2.200000,1.100,1.100000,10,10
19,Premier League,Arsenal,Southampton,2,2.125000,0.750,1.375000,8,8
8,Bundesliga,M'gladbach,Union Berlin,2,2.100000,1.200,0.900000,10,10
9,La Liga,Espanol,Cadiz,2,2.100000,0.900,1.200000,10,10
17,La Liga,Mallorca,Getafe,2,2.100000,1.100,1.000000,10,10
28,Serie A,Salernitana,Sassuolo,2,2.100000,1.200,0.900000,10,10
1,Bundesliga,Hoffenheim,FC Koln,2,2.000000,0.800,1.200000,10,10
32,Serie A,Monza,Fiorentina,2,2.000000,1.300,0.700000,10,10
36,Serie A,Atalanta,Roma,2,2.000000,1.200,0.800000,10,10

##### Common ones

In [934]:
comm = ddgroup.merge(ddoverall, on=['home_team','away_team'])
comm['delta'] = (comm['min_fatti_subiti_x'] - comm['min_fatti_subiti_y']).apply(abs)
comm.sort_values(['min_fatti_subiti_floor_x','delta'], ascending=False)

,competition_x,home_team,away_team,min_fatti_subiti_floor_x,min_fatti_subiti_x,min_goal_fatti_away_subiti_home_x,min_goal_fatti_home_subiti_away_x,n_matches_home_x,n_matches_away_x,competition_y,min_fatti_subiti_floor_y,min_fatti_subiti_y,min_goal_fatti_away_subiti_home_y,min_goal_fatti_home_subiti_away_y,n_matches_home_y,n_matches_away_y,delta
0,Premier League,Arsenal,Southampton,3,3.333333,1.000000,2.333333,3,3,Premier League,2,2.125000,0.750,1.375000,8,8,1.208333
1,Bundesliga,Mainz,Bayern Munich,3,3.250000,1.250000,2.000000,4,4,Bundesliga,2,2.400000,1.000,1.400000,10,10,0.850000
2,La Liga,Valladolid,Girona,3,3.000000,2.000000,1.000000,3,1,La Liga,2,2.900000,1.800,1.100000,10,10,0.100000
14,Premier League,Liverpool,Nott'm Forest,2,2.000000,1.000000,1.000000,1,1,Premier League,2,2.875000,0.750,2.125000,8,8,0.875000
7,La Liga,Sevilla,Villarreal,2,2.500000,2.000000,0.500000,2,3,La Liga,3,3.100000,1.700,1.400000,10,10,0.600000
4,Serie A,Udinese,Cremonese,2,2.800000,1.200000,1.600000,1,5,Serie A,2,2.300000,1.200,1.100000,10,10,0.500000
9,Serie A,Monza,Fiorentina,2,2.500000,1.000000,1.500000,3,2,Serie A,2,2.000000,1.300,0.700000,10,10,0.500000
5,Bundesliga,Leverkusen,RB Leipzig,2,2.666667,1.000000,1.666667,3,3,Bundesliga,2,2.200000,1.100,1.100000,10,10,0.466667
3,Bundesliga,Dortmund,Ein Frankfurt,2,3.000000,0.666667,2.333333,4,3,Bundesliga,2,2.700000,1.200,1.500000,10,10,0.300000
12,Premier League,Newcastle,Tottenham,2,2.333333,1.666667,0.666667,3,1,Premier League,2,2.625000,1.375,1.250000,8,8,0.291667
15,Premier League,Brentford,Aston Villa,2,2.000000,2.000000,0.000000,3,3,Premier League,2,2.250000,1.625,0.625000,8,8,0.250000
8,Premier League,Fulham,Leeds,2,2.500000,1.000000,1.500000,2,4,Premier League,2,2.392857,1.250,1.142857,7,8,0.107143
6,La Liga,Almeria,Ath Bilbao,2,2.500000,1.750000,0.750000,4,4,La Liga,2,2.400000,1.500,0.900000,10,10,0.100000
13,La Liga,Mallorca,Getafe,2,2.000000,1.500000,0.500000,2,3,La Liga,2,2.100000,1.100,1.000000,10,10,0.100000
16,Serie A,Salernitana,Sassuolo,2,2.000000,1.000000,1.000000,3,4,Serie A,2,2.100000,1.200,0.900000,10,10,0.100000
11,Premier League,Crystal Palace,Everton,2,2.333333,0.666667,1.666667,3,3,Premier League,2,2.375000,1.000,1.375000,8,8,0.041667
10,Bundesliga,Freiburg,Schalke 04,2,2.333333,0.666667,1.666667,3,3,Bundesliga,2,2.300000,1.200,1.100000,10,10,0.033333

### N° Goals - UNDER

In [935]:
dd2 = next_matches_with_group.merge(n_goal_group,\
                    left_on=['competition','home_team','team_group_away'],
                    right_on=['competition','main_team','team_group']).drop(columns=['team_group'])\
                        .merge(n_goal_group,\
                    left_on=['competition','away_team','team_group_home'],
                    right_on=['competition','main_team','team_group'], suffixes=['_home','_away'])
dd2['max_goal_fatti_home_subiti_away'] = \
            dd2.apply(lambda row: max(row['avg_goal_fatti_home'],row['avg_goal_subiti_away']), axis=1)
dd2['max_goal_fatti_away_subiti_home'] = \
            dd2.apply(lambda row: max(row['avg_goal_fatti_away'],row['avg_goal_subiti_home']), axis=1)
dd2['max_fatti_subiti'] = dd2['max_goal_fatti_home_subiti_away'] + dd2['max_goal_fatti_away_subiti_home']
dd2['max_fatti_subiti_floor'] = dd2['max_fatti_subiti'].apply(ceil)

#### Group

In [936]:
dd3 = dd2[dd2.max_fatti_subiti_floor < 4]
ddgroup = dd3[['competition','home_team','away_team',\
     'max_fatti_subiti_floor','max_fatti_subiti',\
    'max_goal_fatti_away_subiti_home','max_goal_fatti_home_subiti_away',\
     'n_matches_home','n_matches_away']]\
    .sort_values(['max_fatti_subiti_floor','max_fatti_subiti'], ascending=True)
ddgroup

,competition,home_team,away_team,max_fatti_subiti_floor,max_fatti_subiti,max_goal_fatti_away_subiti_home,max_goal_fatti_home_subiti_away,n_matches_home,n_matches_away
21,Premier League,Crystal Palace,Everton,3,2.444444,0.888889,1.555556,9,11
29,Serie A,Lazio,Torino,3,2.454545,0.636364,1.818182,10,11
32,Serie A,Monza,Fiorentina,3,2.458333,1.333333,1.125000,9,8
10,La Liga,Osasuna,Betis,3,2.555556,1.555556,1.000000,9,10
27,Serie A,Verona,Bologna,3,2.555556,1.555556,1.000000,11,9
33,Serie A,Udinese,Cremonese,3,2.583333,1.000000,1.583333,8,12
12,La Liga,Sociedad,Vallecano,3,2.600000,1.000000,1.600000,10,9
30,Serie A,Sampdoria,Spezia,3,2.666667,1.666667,1.000000,9,7
17,La Liga,Mallorca,Getafe,3,2.700000,1.500000,1.200000,8,10
34,Serie A,Milan,Lecce,3,2.753247,1.181818,1.571429,7,11
25,Premier League,Newcastle,Tottenham,3,2.777778,1.000000,1.777778,9,9
36,Serie A,Atalanta,Roma,3,2.777778,1.666667,1.111111,9,9
28,Serie A,Salernitana,Sassuolo,3,2.800000,1.700000,1.100000,10,10
13,La Liga,Valladolid,Girona,3,2.841270,1.555556,1.285714,9,7
35,Serie A,Juventus,Napoli,3,2.933333,1.600000,1.333333,9,10
24,Premier League,Leicester,Wolves,3,2.954545,1.454545,1.500000,11,10
22,Premier League,Liverpool,Nott'm Forest,3,2.975000,1.100000,1.875000,8,10
8,Bundesliga,M'gladbach,Union Berlin,3,3.000000,1.545455,1.454545,11,10
16,La Liga,Barcelona,Ath Madrid,3,3.000000,0.888889,2.111111,9,9
26,Premier League,Bournemouth,West Ham,3,3.000000,1.375000,1.625000,8,10

#### Overall

In [937]:
dd2 = next_matches_with_group.merge(n_goal_group_last_matches[n_goal_group_last_matches.team_group=='all'],\
                    left_on=['competition','home_team'],
                    right_on=['competition','main_team']).drop(columns=['team_group'])\
                        .merge(n_goal_group_last_matches[n_goal_group_last_matches.team_group=='all'],\
                    left_on=['competition','away_team'],
                    right_on=['competition','main_team'], suffixes=['_home','_away'])
dd2['max_goal_fatti_home_subiti_away'] = \
            dd2.apply(lambda row: max(row['avg_goal_fatti_home'],row['avg_goal_subiti_away']), axis=1)
dd2['max_goal_fatti_away_subiti_home'] = \
            dd2.apply(lambda row: max(row['avg_goal_fatti_away'],row['avg_goal_subiti_home']), axis=1)
dd2['max_fatti_subiti'] = dd2['max_goal_fatti_home_subiti_away'] + dd2['max_goal_fatti_away_subiti_home']
dd2['max_fatti_subiti_floor'] = dd2['max_fatti_subiti'].apply(ceil)

In [938]:
dd3 = dd2[dd2.max_fatti_subiti_floor < 4]
ddoverall = dd3[['competition','home_team','away_team',\
     'max_fatti_subiti_floor','max_fatti_subiti',\
    'max_goal_fatti_away_subiti_home','max_goal_fatti_home_subiti_away',\
     'n_matches_home','n_matches_away']]\
    .sort_values(['max_fatti_subiti_floor','max_fatti_subiti'], ascending=True)
ddoverall

,competition,home_team,away_team,max_fatti_subiti_floor,max_fatti_subiti,max_goal_fatti_away_subiti_home,max_goal_fatti_home_subiti_away,n_matches_home,n_matches_away
27,Serie A,Verona,Bologna,2,2.000,1.300,0.700,10,10
34,Serie A,Milan,Lecce,2,2.000,0.800,1.200,10,10
31,Serie A,Empoli,Inter,3,2.100,1.300,0.800,10,10
12,La Liga,Sociedad,Vallecano,3,2.200,1.000,1.200,10,10
17,La Liga,Mallorca,Getafe,3,2.300,1.200,1.100,10,10
32,Serie A,Monza,Fiorentina,3,2.300,1.300,1.000,10,10
6,Bundesliga,Freiburg,Schalke 04,3,2.400,1.200,1.200,10,10
29,Serie A,Lazio,Torino,3,2.400,1.000,1.400,10,10
8,Bundesliga,M'gladbach,Union Berlin,3,2.500,1.600,0.900,10,10
36,Serie A,Atalanta,Roma,3,2.500,1.600,0.900,10,10
21,Premier League,Crystal Palace,Everton,3,2.625,1.125,1.500,8,8
28,Serie A,Salernitana,Sassuolo,3,2.700,1.500,1.200,10,10
10,La Liga,Osasuna,Betis,3,3.000,1.600,1.400,10,10
24,Premier League,Leicester,Wolves,3,3.000,1.875,1.125,8,8

##### Common ones

In [939]:
ddgroup.merge(ddoverall, on=['home_team','away_team'])

,competition_x,home_team,away_team,max_fatti_subiti_floor_x,max_fatti_subiti_x,max_goal_fatti_away_subiti_home_x,max_goal_fatti_home_subiti_away_x,n_matches_home_x,n_matches_away_x,competition_y,max_fatti_subiti_floor_y,max_fatti_subiti_y,max_goal_fatti_away_subiti_home_y,max_goal_fatti_home_subiti_away_y,n_matches_home_y,n_matches_away_y
0,Premier League,Crystal Palace,Everton,3,2.444444,0.888889,1.555556,9,11,Premier League,3,2.625,1.125,1.500,8,8
1,Serie A,Lazio,Torino,3,2.454545,0.636364,1.818182,10,11,Serie A,3,2.400,1.000,1.400,10,10
2,Serie A,Monza,Fiorentina,3,2.458333,1.333333,1.125000,9,8,Serie A,3,2.300,1.300,1.000,10,10
3,La Liga,Osasuna,Betis,3,2.555556,1.555556,1.000000,9,10,La Liga,3,3.000,1.600,1.400,10,10
4,Serie A,Verona,Bologna,3,2.555556,1.555556,1.000000,11,9,Serie A,2,2.000,1.300,0.700,10,10
5,La Liga,Sociedad,Vallecano,3,2.600000,1.000000,1.600000,10,9,La Liga,3,2.200,1.000,1.200,10,10
6,La Liga,Mallorca,Getafe,3,2.700000,1.500000,1.200000,8,10,La Liga,3,2.300,1.200,1.100,10,10
7,Serie A,Milan,Lecce,3,2.753247,1.181818,1.571429,7,11,Serie A,2,2.000,0.800,1.200,10,10
8,Serie A,Atalanta,Roma,3,2.777778,1.666667,1.111111,9,9,Serie A,3,2.500,1.600,0.900,10,10
9,Serie A,Salernitana,Sassuolo,3,2.800000,1.700000,1.100000,10,10,Serie A,3,2.700,1.500,1.200,10,10
10,Premier League,Leicester,Wolves,3,2.954545,1.454545,1.500000,11,10,Premier League,3,3.000,1.875,1.125,8,8
11,Bundesliga,M'gladbach,Union Berlin,3,3.000000,1.545455,1.454545,11,10,Bundesliga,3,2.500,1.600,0.900,10,10